PCShop/Controllers/PCShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PCShop.Models;

namespace PCShop.Controllers
{
    public class PCShopController : Controller
    {
        Context db = new Context();
        // GET: PCShop
        public ActionResult Index(int ? CategoryID)
        {
            ProductVM pro = new ProductVM();
            if (CategoryID.HasValue)
                pro.Products = db.Products.Where(x => x.CategoryID == CategoryID).ToList();
            else
                pro.Products = db.Products.ToList();

            pro.Categories = db.Categories.ToList();


            if(Session["LogedID"] !=null)
            {
                return View("Index1",pro);
            }

            return View("Index",pro);

        }

        public ActionResult Login()
        {
            return View("Login");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Customer c)
        {
            if (ModelState.IsValid)
            {
                int id;
                var v = db.Customers.Where(a => a.Email.Equals(c.Email) && a.Password.Equals(c.Password)).FirstOrDefault();
                if (v != null)
                {
                    Session["LogedID"] = v.CustomerID.ToString();
                    Session["LoggedEmail"] = v.Email.ToString();
                    Session["id"] = v.CustomerID;

                    id = v.CustomerID;

                    return RedirectToAction("Index");
                }
            }
            return View(c);
        }

        public ActionResult Logout()
        {
            Session.Remove("LogedID");

            //var cart = BookstoreCart.GetCart(HttpContext);
            //cart.EmptyCart();

            return RedirectToAction("Index");
        }

        public ActionResult Register(Customer c)
        {
            return View("Register");
        }

        //POST: Create a new user
        public ActionResult postCreate(string Password, string FirstName, string LastName, string Address, string Email, string City)
        {
            var c = new Customer();
            c.Password = Password;
            c.Name = FirstName;
            c.Surname = LastName;
            c.Email = Email;
            c.Address = Address;
            c.City = City;
            db.Customers.Add(c);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

PCShop/Views/PCShop/Index.cshtml
@using PCShop.Models

@model ProductVM
@{
    ViewBag.Title = "All Products";
}
<h3>   </h3>

<div class="active">
    <a href="/PCShop/Login" class="btn btn-primary">Login</a>
    <a href="/PCShop/Register" class="btn btn-primary">Register</a>
</div>

<div>
    <form>
        <h3><b>Browse: </b></h3>@Html.DropDownListFor(m => m.CategoryID, Model.CategoriesAsSelectListItem)
        <input type="submit" value="Filter" name="SubmitButton" />
    </form>
</div>
<div>
    <table class="table table-bordered table-hover table-striped">
        <tr class="info">
            <th>
                Category
            </th>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
                Details
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Products)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Details)
                </td>
            </tr>
        }

    </table>
</div>

PCShop/Views/PCShop/Index1.cshtml
@using PCShop.Models

@model ProductVM
@{
    ViewBag.Title = "All Products";
}

<a href="/PCShop/Logout" class="btn btn-danger">Logout</a>

<h3><b>Browse: </b></h3>
<div>
    <form>
        @Html.DropDownListFor(m => m.CategoryID, Model.CategoriesAsSelectListItem)
        <input type="submit" value="Filter" name="SubmitButton" />
    </form>
</div>

<div>
    <table class="table table table-bordered table-hover table-striped">
        <tr class="info">
            <th>
                Category
            </th>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
                Details
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Products)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Details)
                </td>
                <td>
                    <a class="btn btn-primary btn-sm" href="/PCShopCart/AddToCart?id=@item.ProductID">Add to Cart</a>
                </td>
            </tr>
        }

    </table>
</div>

PCShop/Views/PCShop/Login.cshtml
@model PCShop.Models.Customer
@{
    ViewBag.Title = "Login";
}

<br />

@using (Html.BeginForm("Login", "PCShop", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    if (@ViewBag.Message != null)
    {
        <div style="border:1px solid red">
            @ViewBag.Message
        </div>
    }
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(a => a.Email)
            @Html.EditorFor(a => a.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(a => a.Email, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.Password)
            @Html.EditorFor(a => a.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(a => a.Password, "", new { @class = "text-danger" })
        </div>
        <br />
        <input class="btn btn-default" type="submit" value="Login" />
    </div>
}

PCShop/Views/PCShop/Register.cshtml
@model PCShop.Models.Customer
@{
    ViewBag.Title = "Register";
}

<br />

<form action="/PCShop/postCreate">

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            </div>
           </div>
            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                </div>
            
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back", "Index")
</div>